### PR TITLE
Restruct the project

### PR DESCRIPTION
**Pull request by Jackhr-arch**
Use Vec to manage the tabs (HashMap does not render in order).
Add a Config tab
Replace some items
Load state from clash core rather file
Generate config file from struct ClashTuiConfig rather Symbols
Warn the user about config or connectivity at startup

Remove some function, bcs I'm not interested in them.
Do Not test Windows build, bcs I don't use.

Current there is a bug, when clash core is offline and try TestClashConfig will freeze the page, but press ESC will quit.

I create this pr bcs I lose interest in it. Maybe I will come back some day.

### CODE REVIEW

**Comment by Jackhr-arch** [comment]
My jod is done.

**Comment by JohanChane** [comment]
I roughly browsed through the source code of pr. Most of the features you added are quite good, and I will add them to clashtui later. I may also test and improve them, but it will take some time as I am currently quite busy and won't be able to do it quickly. You've added a lot of things, no need to rush; enjoyment is the most important (I also want to take it easy for a bit).

Here are some of my suggestions:

1. When configuring the tab to pop up an input box, preset the existing configuration content in the box.
2. The layout of the status bar should be consistent.
3. I think it is necessary to keep Edit, Locate home path, Locate clash config dir, and Stop clashsrv. I use these functions regularly, especially on Windows.

Thank you for improving and expanding clashtui. The further enhancements can be done either by me or you, no rush, we can do it whenever we have time.

**Comment by Jackhr-arch** [comment]
About the removed functions
I wasn't about to use them, and at the beginning the work was quite big, so I just 'comment' them. If anyone is intersted in it, he can do the fix.
About your suggestions
The first is on plan, but I don't get you about the second. If you mean the windows platform, then I hold the same opinion as Removed functions : Anyone who is interested can do the fix.

But that's fine, I'll make edit and open dir work. About the clash service actions, they just moved from global to ClashSrvTab.

**Comment by Jackhr-arch** [comment]
About cron
I have make a special flag `Flags::UpdateOnly`. When it's set to true, clashtui won't setup terminal or init ui set, but just new ClashTuiUtil and execute `update_local_profile` for all local profiles. 
I was planned to get the param from cli (like "`clashtui --update-only`") and use it with `crontab`, but I don't know how to. You can finish this.
I place it at main.rs: fn main `flags.insert(utils::Flags::UpdateOnly, false);`

**Comment by JohanChane** [comment]
> About cron I have make a special flag `Flags::UpdateOnly`. When it's set to true, clashtui won't setup terminal or init ui set, but just new ClashTuiUtil and execute `update_local_profile` for all local profiles. I was planned to get the param from cli (like "`clashtui --update-only`") and use it with `crontab`, but I don't know how to. You can finish this. I place it at main.rs: fn main `flags.insert(utils::Flags::UpdateOnly, false);`

Ok, I will finish it later.

**Comment by Jackhr-arch** [comment]
Add Ci.
Now every push or pr to repo will be automatically tested and generate a release build (`cargo test & cargo build --release`).
Pushing a tag will triger the bot to publish a release on Github with files. You can change its content after it's posted.

**Comment by JohanChane** [comment]
> Add Ci. Now every push or pr to repo will be automatically tested and generate a release build (`cargo test & cargo build --release`). Pushing a tag will triger the bot to publish a release on Github with files. You can change its content after it's posted.

Thanks.

**Comment by Jackhr-arch** [comment]
#### About your replay
> When adding a new configuration item, the original configuration gets overwritten.

I don't get what this means, you mean the clashtui config file or the mihomo config file? I don't remember if I modified this part clearly.

>I don't want clashtui to modify the user's configuration file.
>and the configuration is only one-time

These seem to be confusing for me, too.

**Comment by JohanChane** [comment]
> #### About your replay
> > When adding a new configuration item, the original configuration gets overwritten.
> 
> I don't get what this means, you mean the clashtui config file or the mihomo config file? I don't remember if I modified this part clearly.
> 
> > I don't want clashtui to modify the user's configuration file.
> > and the configuration is only one-time
> 
> These seem to be confusing for me, too.

为了更加明确地说明, 我用中文吧。

> When adding a new configuration item, the original configuration gets overwritten.

我添加在 `ClashTuiConfig` 添加一个成员 `sysproxy_switch` 后, 编译运行然后正常退出 clashtui 后, 原有的 `config.yaml` 的内容会被默认值覆盖。所以我添加了一些提示 https://github.com/JohanChane/clashtui/blob/dev/src/utils/clashtui.rs#L920。

> I don't want clashtui to modify the user's configuration file.
> and the configuration is only one-time

在我的使用体验后, 我觉得没有必要为用户提供一个配置界面。熟悉使用 linux 的用户, 会更加喜欢使用 vim or Atom 等编辑器来完成配置。一些配置项会有一些解析说明。这样会更加高效全面。就目前的配置功能来说, 我用编辑器修改配置项可能导致原有的配置会被覆盖。我知道你的设计思想是让用户通过界面配置即可, 但是我使用起来感觉不习惯, 觉得不方便。而且在我使用的 linux 软件中, 它们一般没有修改我的配置文件且保留我的注释, 也是因为它们没有提供配置界面的原因。我知道后续可以将它做好, 但是后续它的开发和扩展是比较麻烦且无聊的。虽然提供配置界面会降低使用门槛, 但是 clashtui 的用户都是熟悉使用计算机的, 我们没有必要为他们降低使用门槛。

**Comment by Jackhr-arch** [comment]
You're right, I didn't write code about trying to recover from a "corrupted" file. 

I figured that the config file wouldn't change until any new features using a new config item were added, which probably wouldn't happen very often, so I held off this. Clearly I forget it 😂

About the config tab, your word does make sense, user can modify it via some common yaml editor or even some web apps.

Given this, I will mark this tab as desperate. To be honest, this can really simplify the program. I start to like this idea.

I will cherry pick you fix for win into mine, and repost it to GitHub in the next days. 

If you have any ideas, feel free to tell me 😶‍🌫️

**Pull request closed without merging**
